# Generated by Django 4.2.13 on 2024-11-21 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moodtracking', '0002_alter_moodlog_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moodlog',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='moodlog',
            name='sentiment_analysis_result',
        ),
        migrations.AddField(
            model_name='moodlog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='moodlog',
            name='sentiment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='moodlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
