# Generated by Django 4.2.13 on 2024-11-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalcontent',
            name='content_type',
            field=models.CharField(choices=[('Article', 'Article'), ('Video', 'Video')], default='Article', max_length=50),
        ),
        migrations.AddField(
            model_name='educationalcontent',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
